services:
  - type: web
    name: microapps
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python production.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.9.0 